### ISSUE TITLE
change participant after a person is in the system

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#742]
Hi,

I did some testing to see if the 'change participant' works, it does until after clicking on 'accept transfer'. Then this error occurs. 

https://ejc2016.ers.inbaz.org/admin/package/accept-participant-change?package_id=524&user_id=533

the same error occurs at trying this through 'move package to another order' .

Is there a differents between these two options? They seem to do the same to me.

**Comment by inbaz** [comment]
TODO: add a validator to check if a participant with the given e-mail address already exists. Add an appropriate error message. Suggestions for a nice error message are welcome.

**Comment by inbaz** [comment]
There is a difference because think of having multiple participants within a single order. If you change one participants details which does not have anything to do with this group the e-ticket of this participant would still be sent to the buyer of the whole order. Therefore it was needed to be able to transfer tickets completely into a new order.

**Comment by inbaz** [comment]
I corrected the functionality of change participant in 0.4.51

**Comment by Tobias-Horstmann** [comment]
I tested this with version 0.4.52.  I tried to "Change Participant for Item 2N9PF184", from participant "tobias testing3" to "Tobias Horstmann" and get following error message: 

"Additional information:
Doctrine\ORM\ORMInvalidArgumentException

File:

    /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:204

Message:

    Expected value of type "ErsBase\Entity\Status" for association field "ErsBase\Entity\Item#$status", got "string" instead.

Stack trace:

    #0 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2229): Doctrine\ORM\ORMInvalidArgumentException::invalidAssociation(Object(Doctrine\ORM\Mapping\ClassMetadata), Array, 'transferred')
    #1 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1693): Doctrine\ORM\UnitOfWork->cascadePersist(Object(DoctrineORMModule\Proxy\__CG__\ErsBase\Entity\Item), Array)
    #2 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2232): Doctrine\ORM\UnitOfWork->doPersist(Object(DoctrineORMModule\Proxy\__CG__\ErsBase\Entity\Item), Array)
    #3 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1693): Doctrine\ORM\UnitOfWork->cascadePersist(Object(ErsBase\Entity\ItemPackage), Array)
    #4 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2218): Doctrine\ORM\UnitOfWork->doPersist(Object(ErsBase\Entity\ItemPackage), Array)
    #5 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1693): Doctrine\ORM\UnitOfWork->cascadePersist(Object(ErsBase\Entity\Item), Array)
    #6 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1630): Doctrine\ORM\UnitOfWork->doPersist(Object(ErsBase\Entity\Item), Array)
    #7 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(579): Doctrine\ORM\UnitOfWork->persist(Object(ErsBase\Entity\Item))
    #8 /home/ejc2016/www/ejc2016.ers.inbaz.org/module/Admin/src/Admin/Controller/ItemController.php(561): Doctrine\ORM\EntityManager->persist(Object(ErsBase\Entity\Item))
    #9 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Admin\Controller\ItemController->acceptParticipantChangeAction()
    #10 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
    #11 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #12 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #13 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #14 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
    #15 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
    #16 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #17 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #18 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #19 /home/ejc2016/www/ejc2016.ers.inbaz.org/public/index.php(18): Zend\Mvc\Application->run()
    #20 {main}
"
