### ISSUE TITLE
Search for anything on onsite page results in exception

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#751]
The exception is:
```
[Semantical Error] line 0, col 64 near 'u INNER JOIN': Error: Class ErsBase\Entity\Package has no association named participant
```

**Comment by inbaz** [comment]
fixed in master

**Comment by PiQuer** [comment]
Now searching for a non-existent order works without exception and correctly returns 0 results. Searching for an existing Name or order number results in the following exception:

```
Zend\ServiceManager\Exception\ServiceNotFoundException

File:

    /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:555

Message:

    Zend\ServiceManager\ServiceManager::get was unable to fetch or create an instance for PreReg\Service\AgegroupService:ticket

Stack trace:

    #0 /home/ejc2016/www/ejc2016.ers.inbaz.org/module/OnsiteReg/src/OnsiteReg/Controller/PackageController.php(38): Zend\ServiceManager\ServiceManager->get('PreReg\\Service\\...')
    #1 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): OnsiteReg\Controller\PackageController->detailAction()
    #2 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
    #3 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #4 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #5 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #6 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
    #7 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
    #8 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #9 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #10 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #11 /home/ejc2016/www/ejc2016.ers.inbaz.org/public/index.php(18): Zend\Mvc\Application->run()
    #12 {main}
```

To reproduce: search for "max muster" or "H6U8X205" (exception) compared to "max mister" or "H6U8X206" (no exception) on preprod.

**Comment by inbaz** [comment]
fixed in new version as discussed.
