### ISSUE TITLE
Manual Matching error

### ISSUE THREAD

**Issue by Tobias-Horstmann** [inbaz/ers#779]
v 0.4.53
I tried to manually match orders. I created an own bank account ("Tobias Private Bank"), had uploaded a csv file and set the format to match the columns of the manual csv file. Then I conutinued to the manual matching, chose a match ("tobias tocancel") and got to the accept match page and clicked on "match -> paid". Then I got following error:

"
An error occurred
Sorry!

The page you are looking for doesn't exist. If you think this is an error, please let us know at info@ejc2016.org.

If you encounter any error with this system, please send us a full copy of this page.
You might be looking for:

```
the products page
your current shopping cart
the login to access your previous purchases
```

An error occurred during execution; please try again later.
Additional information:
Doctrine\ORM\ORMInvalidArgumentException

File:

```
/home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:204
```

Message:

```
Expected value of type "ErsBase\Entity\Status" for association field "ErsBase\Entity\Item#$status", got "string" instead.
```

Stack trace:

```
#0 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2229): Doctrine\ORM\ORMInvalidArgumentException::invalidAssociation(Object(Doctrine\ORM\Mapping\ClassMetadata), Array, 'paid')
#1 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1693): Doctrine\ORM\UnitOfWork->cascadePersist(Object(ErsBase\Entity\Item), Array)
#2 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2232): Doctrine\ORM\UnitOfWork->doPersist(Object(ErsBase\Entity\Item), Array)
#3 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1693): Doctrine\ORM\UnitOfWork->cascadePersist(Object(ErsBase\Entity\ItemPackage), Array)
#4 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2218): Doctrine\ORM\UnitOfWork->doPersist(Object(ErsBase\Entity\ItemPackage), Array)
#5 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1693): Doctrine\ORM\UnitOfWork->cascadePersist(Object(ErsBase\Entity\Item), Array)
#6 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1630): Doctrine\ORM\UnitOfWork->doPersist(Object(ErsBase\Entity\Item), Array)
#7 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(579): Doctrine\ORM\UnitOfWork->persist(Object(ErsBase\Entity\Item))
#8 /home/ejc2016/www/ejc2016.ers.inbaz.org/module/Admin/src/Admin/Controller/MatchingController.php(258): Doctrine\ORM\EntityManager->persist(Object(ErsBase\Entity\Item))
#9 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Admin\Controller\MatchingController->acceptAction()
#10 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#11 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#12 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#15 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#16 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#17 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 /home/ejc2016/www/ejc2016.ers.inbaz.org/public/index.php(18): Zend\Mvc\Application->run()
#20 {main}
```

report a bug
Version: 0.4.53

© 2016 by European Juggling Association All rights reserved.
"

**Comment by inbaz** [comment]
This needs to be checked again, I think I have fixed all status parts in the system now.
